conconexp/conconexp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/concon'}, name='logout'),
    url(r'^reset_password/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conconexp/home/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views
from views import IndexView, ProfileView

app_name = 'home'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^conflict/$', views.conflict, name='conflict'),
    url(r'^conflict/(?P<conf_id>\d+)/(?P<model_name>[a-z]+)/$', views.delete_conflict, name='delete_conflict'),
    url(r'^intro/$', TemplateView.as_view(template_name='home/intro.html'), name='intro'),
    url(r'^contact/$', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
    url(r'^terms/$', TemplateView.as_view(template_name='home/terms.html'), name='terms'), 
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/(?P<con_id>\d+)/$', views.delete_contract, name='delete-contract'),
    url(r'^contract/(?P<con_id>\d+)/$', views.contract, name='contract'),
    url(r'^contract/(?P<con_id>\d+)/(?P<model_name>[a-z]+)/$', views.contract, name='contract_2'),
    url(r'^model_description/$', TemplateView.as_view(template_name='home/introducing_models.html'), name='model_description'),
    url(r'^new_conflicts/$', views.new_conflicts, name='new_conflicts'),
    url(r'^delete_conf/$', views.delete_conf, name='delete_conf'),
    url(r'^submit_conf/$', views.submit_conf, name='submit_conf'),
]

conconexp/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    # last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password1', 'password2', )


class UploadFileForm(forms.Form):

    title = forms.CharField(max_length=100)
    file = forms.FileField()

conconexp/home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os, math
from forms import SignUpForm
from models import ConflictTypes
from django.conf import settings
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.core.paginator import PageNotAnInteger
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, ListView
from create_conflicts import ConflictCreator, remove_norm
from django.http import HttpResponse, HttpResponseRedirect
from scripts import insert_conflicts, Contract, embedding_model
from models import AuthUser, Contracts, Clauses, Conflicts, Classifiers
from scripts import insert_contract, cnn_model, msc_model, save_contract
from django.http import JsonResponse

BACKUP_FOLDER = os.path.join(settings.BASE_DIR, 'media/backup_contracts')
CONF_TYPES = {
    'simple': 1,
    'context': 2,
    'conditional': 3
}


class IndexView(TemplateView):

    template_name = "home/index.html"


def submit_conf(request):

    # Insert new conflict from user.

    if request.is_ajax():

        try:
            # Get info sent via ajax.
            con_id = request.GET.get('con_id', None)
            clause_id_1 = request.GET.get('clause_id_1', None)
            clause_id_2 = request.GET.get('clause_id_2', None)
            added_by = request.GET.get('added_by', None)
            confidence = request.GET.get('confidence', None)

            # Get the objects from each element.
            con_id = Contracts.objects.get(con_id=con_id)
            clause_id_1 = Clauses.objects.get(clause_id=int(clause_id_1))
            clause_id_2 = Clauses.objects.get(clause_id=int(clause_id_2))
            added_by = AuthUser.objects.get(id=int(added_by))

            # Add conflict to database.
            ins = Conflicts(con=con_id, clause_id_1=clause_id_1,
                clause_id_2=clause_id_2, added_by=added_by,
                confidence=int(confidence))

            ins.save()

            return JsonResponse({'done': True})
        except:
            return JsonResponse({'done': False})
        
    else:
        return JsonResponse({'done': False})



def delete_conf(request):

    if request.is_ajax():

        conf_id = request.GET.get('conf_id', None)
        
        # Delete conflict.
        try:
            Conflicts.objects.filter(conf_id=conf_id).delete()
            done = True
        except:
            return HttpResponse("This route only handles AJAX requests")

        data = {
            'done': done
        }

        return JsonResponse(data)


def register(request):

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/concon')
    else:
        form = SignUpForm()
    return render(request, 'home/register.html', {'form': form})


class ProfileView(ListView):
    
    
    model = Contracts
    template_name = 'home/profile.html'
    paginate_by = 10.0 #this number has to be in double due to math.ceil

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        user_id = self.request.user.id
        queryset = Contracts.objects.filter(added_by=user_id).order_by(
            'reg_date')
        
        page = self.request.GET.get('page', 1)
        paginator = Paginator(queryset, self.paginate_by)

        try:
            file_contracts = paginator.page(page)
        except PageNotAnInteger:
            file_contracts = paginator.page(1)
        except EmptyPage:
            file_contracts = paginator.page(paginator.num_pages)

        context['contracts'] = file_contracts
        # Variable that stores the numberOfContractsOfTheUser division
        # how many contacts per page
        context['contracts_per_page'] = math.ceil(len(queryset
        )/self.paginate_by)


        return context


def delete_contract(request, con_id):

    # Find the path to reach the contract.
    del_contract = Contracts.objects.get(con_id=con_id)
    contract_path = del_contract.path_to_file
    filename = os.path.basename(contract_path)

    # Move the contract to a backup folder.
    if not os.path.exists(BACKUP_FOLDER):
        os.makedirs(BACKUP_FOLDER)
    os.rename(contract_path, os.path.join(BACKUP_FOLDER, filename))

    # Delete clauses from contract.
    del_clauses = Clauses.objects.filter(con=con_id)
    del_clauses.delete()

    # Delete contract.
    del_contract.delete()

    return HttpResponseRedirect(reverse('home:profile'))


def delete_conflict(request, conf_id, model_name):

    # Find conflict and remove it.
    del_conflict = Conflicts.objects.get(conf_id=conf_id)
    con_id = del_conflict.con.con_id
    del_conflict.delete()

    return HttpResponseRedirect(reverse('home:contract_2', args=[con_id,
     model_name]))


def contract(request, con_id, model_name=[]):

    # Get contract information.
    contract = Contracts.objects.get(con_id=con_id)
    contract_name = contract.con_name

    if request.method == 'POST' or model_name:
        # Deal the information receive by POST.

        # Get selected model.
        if not model_name:
            model_name = request.POST.get('select_model', '')

        # Find conflicts using the selected model.
        if model_name == "cnn":

            # Get classifier id.
            classifier_obj = Classifiers.objects.get(
                classifier_name='CNN Model')

            # Check if exists a previous set of annotated conflicts.
            conflicts_query = Conflicts.objects.filter(con_id=con_id,
                classifier=classifier_obj.pk)
            
            if conflicts_query:

                cntrct = Contract(con_id)
                cntrct.process_clauses()
                cls_obj = cntrct.clause_ranges
                clauses = cntrct.clauses

                conflicts = []

                for conflict in conflicts_query:

                    conflicts.append((conflict.conf_id,
                        conflict.clause_id_1.clause_id,
                        conflict.clause_id_2.clause_id, conflict.confidence))

            else:
                cls_obj, clauses, conflicts = cnn_model(con_id)
                conflicts = insert_conflicts(con_id, conflicts,
                    classifier_obj)

        elif model_name == "msc":

            # Get classifier id.
            classifier_obj = Classifiers.objects.get(
                classifier_name='Rule-Based Model')

            # Check if exists a previous set of annotated conflicts.
            conflicts_query = Conflicts.objects.filter(con_id=con_id,
                classifier=classifier_obj.pk)
            
            if conflicts_query:

                cntrct = Contract(con_id)
                cntrct.process_clauses()
                cls_obj = cntrct.clause_ranges
                clauses = cntrct.clauses

                conflicts = []

                for conflict in conflicts_query:

                    conflicts.append((conflict.conf_id,
                        conflict.clause_id_1.clause_id,
                        conflict.clause_id_2.clause_id, conflict.confidence))

            else:
                cls_obj, clauses, conflicts = msc_model(con_id)
                conflicts = insert_conflicts(con_id, conflicts,
                    classifier_obj)
    
        elif model_name == "emb":

            # Get classifier id.
            classifier_obj = Classifiers.objects.get(
                classifier_name='Embedding Model')

            # Check if exists a previous set of annotated conflicts.
            conflicts_query = Conflicts.objects.filter(con_id=con_id,
                classifier=classifier_obj.pk)

            print "Conflicts_query", conflicts_query

            if conflicts_query:

                cntrct = Contract(con_id)
                cntrct.process_clauses()
                cls_obj = cntrct.clause_ranges
                clauses = cntrct.clauses

                conflicts = []

                for conflict in conflicts_query:

                    conflicts.append((conflict.conf_id,
                        conflict.clause_id_1.clause_id,
                        conflict.clause_id_2.clause_id, conflict.confidence))

            else:
                cls_obj, clauses, conflicts = embedding_model(con_id)
                conflicts = insert_conflicts(con_id, conflicts,
                    classifier_obj)

        conflicts.sort(key=lambda conf: conf[3], reverse=True)

        conf_type_elems = get_conf_types()

        context = {
                    'con_name': contract_name,
                    'cls_obj': cls_obj,
                    'clauses': clauses,
                    'conflicts': conflicts,
                    'selected_model': model_name,
                    'conf_types': conf_type_elems,
                    }

        # Return context.
        return render(request, 'home/contract.html', context)

    context = {'contract': contract, 'con_name': contract_name}    

    # Return context.
    return render(request, 'home/contract.html', context)


def get_user_obj(request):
    # Get info to insert contract into table.
    user_id = request.user.id
    return AuthUser.objects.get(id=user_id).pk


def conflict(request):

    if request.method == 'POST' and request.FILES['up_file']:

        # Get selected model.
        model_name = request.POST.get('select_model', '')

        # Save file to a defined path.
        up_file = request.FILES['up_file']
        code, string = save_contract(up_file, request.user.id)

        if code == 'ERROR' or code == 'WARNING':

            context = {

conconexp/home/templates/home/base.html
<!DOCTYPE HTML>
<!--
    Dimension by HTML5 UP
    html5up.net | @ajlkn
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
    <head>
        <title>ConCon</title>
        <meta charset="utf-8" />

        {% load static %}
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

        <link rel="stylesheet" href="../../{% static 'home/assets/css/main.css' %}"/>
        <link rel="stylesheet" href="../../{% static 'home/assets/css/conflict.css' %}"/>
            <!-- for IE and Android native browser support -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>

        <!-- CSS -->
        <!-- <link rel="stylesheet" type="text/css" href="diff2html/dist/diff2html.css"> -->

        <!-- Javascripts -->
        <!-- <script type="text/javascript" src="diff2html/dist/diff2html.js"></script> -->
        <script src="../../{% static 'home/assets/js/jquery.min.js' %}"></script>

<!--    <script src="{% static 'node_modules/sweetalert2/dist/sweetalert2.min.js' %}"></script>
        <link rel="stylesheet" href="node_modules/sweetalert2/dist/sweetalert2.min.css"> -->
        <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
        <noscript><link rel="stylesheet" href="../../{% static 'home/assets/css/noscript.css' %}" /></noscript>
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script> -->
        
        <script type="text/javascript">
            var url_del = "{% url 'home:delete_conf' %}";
            var url_sub = "{% url 'home:submit_conf' %}";
        </script>

        <script src="../../{% static 'home/js/main_functions.js' %}"></script>

    </head>
    <body>

        <div id="wrapper2" class="padding-on-extra-large-screens-header">
            
                {% if user.is_authenticated %}
                <header id="header">
                    <h3>
                        Hi, {{ user.username }}!</h3>
                        <nav>
                        <ul>
                            <li><a href="{% url 'home:index' %}">Home</a></li>
                            <li><a href="{% url 'home:intro' %}">Intro</a></li>
                            <li><a href="{% url 'home:conflict' %}">Conflict</a></li>
                            <li><a href="{% url 'home:profile' %}">Profile</a></li>
                            <li><a href="{% url 'home:contact' %}">Contact</a></li>
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                        </nav>
                 </header>   
                {% else %}
                 <header id=header class="not-autenticated-user-header">
                    <nav>
                    <ul>
                        <li><a href="{% url 'home:index' %}">Home</a></li>
                        <li><a href="{% url 'home:intro' %}">Intro</a></li>
                        <li><a href="{% url 'home:contact' %}">Contact</a></li>
                        <li><a href="{% url 'login' %}">Login</a></li>
                    </ul>
                    </nav>
                </header>
                {% endif %}
            


            {% block content %}            
            {% endblock %}
  </div>
        <!-- BG -->
      <div id="bg"></div>

          <div class="footer_copyright">
             <!-- <a href="https://github.com/mir-pucrs/concon-front-end" style="text-decoration: none; margin-right: 5px;"><img src="{% static 'home/images/github-mark.svg' %}" width="29" height="32"  title="Github link"></a> -->
             <a href="https://twitter.com/share" class="twitter-share-button" data-text="Check for contract conflicts using deep learning http://lsa.pucrs.br/concon" data-hashtags="contracts" data-show-count="false"></a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
             <iframe  class="facebook-share-button"  src="https://www.facebook.com/plugins/share_button.php?href=http%3A%2F%2Flsa.pucrs.br%2Fconconexp%2F&layout=button&size=small&mobile_iframe=true&width=59&height=20&appId" scrolling="no" allowTransparency="true"></iframe><br>
             <small  style="font-size: 0.4rem">&copy; Design: <a href="https://html5up.net" style="font-size: 0.4rem">HTML5 UP</a></small>
          </div>

	<div class="modal"><!-- Place at bottom of page --></div>
        <!-- Scripts -->
        <script src="../../{% static 'home/assets/js/jquery.min.js' %}"></script>
        <script src="../../{% static 'home/assets/js/skel.min.js' %}"></script>
        <script src="../../{% static 'home/assets/js/util.js' %}"></script>
        <script src="../../{% static 'home/assets/js/main.js' %}"></script>
    
    </body>
</html>

conconexp/home/templates/home/conflict.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

{% load home_extras %}
            <div id="wrapper2" class="padding-on-extra-large-screens"> 
                <article id="conflict" class="active" style="display: block;width:auto">
                    <div class="table-wrapper">

            {% if message %}

                <h3 class="alert"><strong style="color: #e74c3c;font-weight: bolder;">{{ message }}</strong></h3>

            {% endif %}

            {% if clauses %}

                {% if conflicts %}

                    <h4 id='test_text'>Conflicts</h4>

                    <select id="selector">
                        <option value="none">-</option>

                        {% for conflict in conflicts %}

                            <option class="conflict" value="{{ conflict|get_index:0 }}_{{ conflict|get_index:1 }}_{{ conflict|get_index:2 }}">{{ conflict|get_index:1 }} - {{ conflict|get_index:2 }} Confidence: {{ conflict|get_index:3 }}%</option>

                        {% endfor %}
                        
                    </select>

                    <p></p>
                    <p></p>

                {% else %}
                    <h4>No conflicts found!</h4>
                {% endif %}

                <div class = "row">
                    <div id='first_table' style=" overflow: auto; height: 400px;  width: 50%; float: left;">
                            <table id="table1" ><!--style="height: 400px;"> -->
                                <tbody>
                                    {% for cls in cls_obj %}
                                        <tr id='first_{{ cls.clause_id }}'>
                                            <td>
                                                {{ cls.clause_id }}
                                            </td>                                    
                                            <td>
                                                {{ clauses|get_text:cls.clause_id }}
                                            </td>                                        
                                        </tr>                                  
                                    {% endfor %}
                                </tbody>
                             </table>
                        </div>                                   
                    <div id='second_table' style="overflow: auto; height: 400px; width: 50%; float: right; ">
                           <table id="table2">
                                <tbody>
                                    {% for cls in cls_obj %}
                                        <tr id="second_{{ cls.clause_id }}">

                                            <td>
                                                {{ cls.clause_id }}
                                            </td>
                                            
                                            <td>
                                                {{ clauses|get_text:cls.clause_id }}
                                            </td>                                        
                                        </tr>                                
                                    {% endfor %}                      
                                </tbody>
                            </table>
                    </div>
               </div>

            {% endif %}

                        <div class="alt">    
                
                                <h4><a href="{% url 'home:new_conflicts' %}">Create New Conflicts</a></h4>

                                <p>Please, upload a contract to start our processing.</p>
                                 
                                <p>Have no contracts but want to test? <a href="https://github.com/JoaoPauloAires/potential-conflict-identifier/tree/master/code/data/manufacturing" target='_blank'><b>Here</b></a> we have some contracts.</p>

                                <form id="file_form" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <span>
                                        Select a Model to use. 
                                    </span>

                                    <select name="select_model">
                                        <option value="emb">
                                            Embedding model
                                        </option>
                                        <option value="cnn">
                                            CNN model
                                        </option>
                                        <option value="msc">
                                            Rule-based model
                                        </option>         
                                    </select>
                                    <br/>
                                    <!-- estava assim antes(o novo ta abaixo), o id é diferente, nao sei se esse id interfere em algo, mas acho que nao<input type="file" name="up_file" id="fileToUpload"> data: 28/07/2017 by Catarina Nogueira-->
                                  
                                    
                                     <!--choose file button-->
                                    <input type="file" name="up_file" id="file" class="inputfile" />
                                    <label for="file">Choose a file</label>
                                     <!--choose file button-->
                                     
                                    <!--upload button-->
                                    <input type="submit" value="Upload" id='upload_button' name="up_file">
                                    <!--upload button-->
                                </form>
                                </tr>

                                
                                <p>Check our <a href="{% url 'home:model_description' %}">model description</a>.</p>

                                <!-- <br/>
                                <p>
                                    <a href="{% url 'home:profile' %}}">Check the contracts you've already uploaded.</a>
                                </p> -->
                                

                      
                        </div>
                    </div>
                
                </article>
            </div>
{% endblock %}

conconexp/home/templates/home/index.html
{% extends 'home/base.html' %}

{% block content %}

            <!-- Header -->
            <div class="padding-on-extra-large-screens no-min-height">
                <header id="header">
                    <div class="content">
                        <div class="inner">
                            <h1>Contract Conflicts</h1>
                            <p><!--[-->Finding contractual conflicts <!--]--><br />
                             faster than humans<!--[--><!--]--></p>
                        </div>
                    </div>
                </header>
            </div>

{% endblock %}

conconexp/home/templates/home/intro.html
{% extends 'home/base.html' %}

{% block content %}

                {% load static %}                
                <!-- Intro -->
                <div class="padding-on-extra-large-screens"> 
                    <header id="header">
                        <div class="content content-with-explanation">
                            <div class="inner">
                                <article id="intro">
                                    <center><h2 class="major">Intro</h2></center>
                                    <p>
                                        Contracts and electronic contracts consist of a set of norms defining what is expected from the parties during the contract validation.
                                        However, norms may conflict between each other in two ways, first, by presenting different deontic meanings applied to the same context and the same party, such as permission x obligation, permission x prohibition, and obligation x prohibition.
                                        Second, conflicts may arise due to conflicting norm conditions or norm descriptions.
                                        Such conflicts create a contract inconsistency that can invalidate the conflicting norms and even contracts.
                                    </p>
                                    <p> 
                                        In this project, we aim to develop an approach to reason about complex norms in natural language documents, typically contracts, and detect norm conflicts and contract inconsistencies.
                                    </p>

                                    <p>
                                        Check out the description of our models <a href="{% url 'home:model_description' %}">here</a>!
                                    </p>
                                </article>
                            </div>  
                        </div>
                </header>
            </div>
{% endblock %}

conconexp/home/templates/home/profile.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}
<div id="wrapper2" class="padding-on-extra-large-screens"> 
    <!-- <header id="header">  -->
        <div class="content content-of-user-contracts">
            <div class="inner">
    <article id="profile" class="active" style="display: block;width:auto">
    
        <div class="table-wrapper" >

            <div>

                {% if contracts %}
                    <table class="table table-bordered">
                        
                        <thead>
                            <tr>
                                <th>
                                    Contract ID
                                </th>
                                <th>
                                    Contract Name
                                </th>
                                <th>
                                    Options
                                </th>
                            </tr>
                        </thead>  

                        <tbody>
                            
                            <h3 class="title-of-table">
                                Your contracts:
                            </h3>

                            {% for contract in contracts %}
                                <tr>

                                    <td>
                                        {{ contract.con_id }}
                                    </td>

                                    <td>
                                        <a class="con_name" href="{% url 'home:contract' contract.con_id %}" title="Click to find conflicts">{{ contract.con_name }}</a>
                                    </td>

                                    <td>
                                        <a href="{% url 'home:delete-contract' contract.con_id %}">Delete</a> <!-- <a href="#">Download</a> | -->
                                    </td>

                                </tr>
                            {% endfor %}

                        </tbody>

                    </table>

                    {% if is_paginated %}
                      <ul class="pagination">
                        {% if page_obj.has_previous %}
                          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                          <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                           {% if i <= contracts_per_page %} 
                                {% if page_obj.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            {% if page_obj.next_page_number <= contracts_per_page %}
                                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                {% else %}
                                    <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        {% endif %}
                      </ul>
                    {% endif %}

                {% else %}

                    <h2>
                        You didn't upload any contract yet.
                    </h2>
                    <center>
                        <p>
                            Please, <a href="{% url 'home:conflict' %}">upload</a> a contract to start.
                        </p>    
                    </center>
                    
                {% endif %}

            </div>

        </div>

    </article>
    </div>  
        </div>                       
    <!-- </header> -->
</div>
{% endblock %}